(define (problem problemPDDL)
    (:domain blocks-domain)
    (:requirements :disjunctive-preconditions :equality :negative-preconditions :strips :typing)
    (:objects a b c d e t1 t2 t3 t4 t5 - block)
    (:init (clear e) (emptyhand) (on a t1) (on b a) (on c b) (on d c) (on e d) (table t1) (table t2) (table t3) (table t4) (table t5))
    (:goal (and (on a t1) (on b t2) (on c t3) (on d t4) (on e t5)))
)